<?php

namespace jimmlog\helper;

/**
 * Country helper for static access country data like ISO 3166-1 alpha-2 code and english short countries name
 *
 * Class CountryHelper
 * @package jimmlog\helper
 */
class CountryHelper
{

    /**
     * Array of ISO 3166-1 alpha-2 countries code
     * @var array
     */
    protected static $isoList = [
        0 => '--',
        1 => 'AF',
        2 => 'AX',
        3 => 'AL',
        4 => 'DZ',
        5 => 'AS',
        6 => 'AD',
        7 => 'AO',
        8 => 'AI',
        9 => 'AQ',
        10 => 'AG',
        11 => 'AR',
        12 => 'AM',
        13 => 'AW',
        14 => 'AC',
        15 => 'AU',
        16 => 'AT',
        17 => 'AZ',
        18 => 'BS',
        19 => 'BH',
        20 => 'BD',
        21 => 'BB',
        22 => 'BY',
        23 => 'BE',
        24 => 'BZ',
        25 => 'BJ',
        26 => 'BM',
        27 => 'BT',
        28 => 'BO',
        29 => 'BA',
        30 => 'BW',
        31 => 'BR',
        32 => 'IO',
        33 => 'VG',
        34 => 'BN',
        35 => 'BG',
        36 => 'BF',
        37 => 'BI',
        38 => 'KH',
        39 => 'CM',
        40 => 'CA',
        41 => 'IC',
        42 => 'CV',
        43 => 'BQ',
        44 => 'KY',
        45 => 'CF',
        46 => 'EA',
        47 => 'TD',
        48 => 'CL',
        49 => 'CN',
        50 => 'CX',
        51 => 'CC',
        52 => 'CO',
        53 => 'KM',
        54 => 'CG',
        55 => 'CD',
        56 => 'CK',
        57 => 'CR',
        58 => 'CI',
        59 => 'HR',
        60 => 'CU',
        61 => 'CW',
        62 => 'CY',
        63 => 'CZ',
        64 => 'DK',
        65 => 'DG',
        66 => 'DJ',
        67 => 'DM',
        68 => 'DO',
        69 => 'EC',
        70 => 'EG',
        71 => 'SV',
        72 => 'GQ',
        73 => 'ER',
        74 => 'EE',
        75 => 'ET',
        76 => 'FK',
        77 => 'FO',
        78 => 'FJ',
        79 => 'FI',
        80 => 'FR',
        81 => 'GF',
        82 => 'PF',
        83 => 'TF',
        84 => 'GA',
        85 => 'GM',
        86 => 'GE',
        87 => 'DE',
        88 => 'GH',
        89 => 'GI',
        90 => 'GR',
        91 => 'GL',
        92 => 'GD',
        93 => 'GP',
        94 => 'GU',
        95 => 'GT',
        96 => 'GG',
        97 => 'GN',
        98 => 'GW',
        99 => 'GY',
        100 => 'HT',
        101 => 'HN',
        102 => 'HK',
        103 => 'HU',
        104 => 'IS',
        105 => 'IN',
        106 => 'ID',
        107 => 'IR',
        108 => 'IQ',
        109 => 'IE',
        110 => 'IM',
        111 => 'IL',
        112 => 'IT',
        113 => 'JM',
        114 => 'JP',
        115 => 'JE',
        116 => 'JO',
        117 => 'KZ',
        118 => 'KE',
        119 => 'KI',
        120 => 'XK',
        121 => 'KW',
        122 => 'KG',
        123 => 'LA',
        124 => 'LV',
        125 => 'LB',
        126 => 'LS',
        127 => 'LR',
        128 => 'LY',
        129 => 'LI',
        130 => 'LT',
        131 => 'LU',
        132 => 'MO',
        133 => 'MK',
        134 => 'MG',
        135 => 'MW',
        136 => 'MY',
        137 => 'MV',
        138 => 'ML',
        139 => 'MT',
        140 => 'MH',
        141 => 'MQ',
        142 => 'MR',
        143 => 'MU',
        144 => 'YT',
        145 => 'MX',
        146 => 'FM',
        147 => 'MD',
        148 => 'MC',
        149 => 'MN',
        150 => 'ME',
        151 => 'MS',
        152 => 'MA',
        153 => 'MZ',
        154 => 'MM',
        155 => 'NA',
        156 => 'NR',
        157 => 'NP',
        158 => 'NL',
        159 => 'NC',
        160 => 'NZ',
        161 => 'NI',
        162 => 'NE',
        163 => 'NG',
        164 => 'NU',
        165 => 'NF',
        166 => 'KP',
        167 => 'MP',
        168 => 'NO',
        169 => 'OM',
        170 => 'PK',
        171 => 'PW',
        172 => 'PS',
        173 => 'PA',
        174 => 'PG',
        175 => 'PY',
        176 => 'PE',
        177 => 'PH',
        178 => 'PN',
        179 => 'PL',
        180 => 'PT',
        181 => 'PR',
        182 => 'QA',
        183 => 'RE',
        184 => 'RO',
        185 => 'RU',
        186 => 'RW',
        187 => 'WS',
        188 => 'SM',
        189 => 'ST',
        190 => 'SA',
        191 => 'SN',
        192 => 'RS',
        193 => 'SC',
        194 => 'SL',
        195 => 'SG',
        196 => 'SX',
        197 => 'SK',
        198 => 'SI',
        199 => 'SB',
        200 => 'SO',
        201 => 'ZA',
        202 => 'GS',
        203 => 'KR',
        204 => 'SS',
        205 => 'ES',
        206 => 'LK',
        207 => 'BL',
        208 => 'SH',
        209 => 'KN',
        210 => 'LC',
        211 => 'MF',
        212 => 'PM',
        213 => 'VC',
        214 => 'SD',
        215 => 'SR',
        216 => 'SJ',
        217 => 'SZ',
        218 => 'SE',
        219 => 'CH',
        220 => 'SY',
        221 => 'TW',
        222 => 'TJ',
        223 => 'TZ',
        224 => 'TH',
        225 => 'TL',
        226 => 'TG',
        227 => 'TK',
        228 => 'TO',
        229 => 'TT',
        230 => 'TA',
        231 => 'TN',
        232 => 'TR',
        233 => 'TM',
        234 => 'TC',
        235 => 'TV',
        236 => 'UM',
        237 => 'VI',
        238 => 'UG',
        239 => 'UA',
        240 => 'AE',
        241 => 'GB',
        242 => 'US',
        243 => 'UY',
        244 => 'UZ',
        245 => 'VU',
        246 => 'VA',
        247 => 'VE',
        248 => 'VN',
        249 => 'WF',
        250 => 'EH',
        251 => 'YE',
        252 => 'ZM',
        253 => 'ZW',
    ];

    /**
     * Array of english short countries name
     * @var array
     */
    protected static $nameList = [
        0 => 'Unknown',
        1 => 'Afghanistan',
        2 => 'Aland Islands',
        3 => 'Albania',
        4 => 'Algeria',
        5 => 'American Samoa',
        6 => 'Andorra',
        7 => 'Angola',
        8 => 'Anguilla',
        9 => 'Antarctica',
        10 => 'Antigua & Barbuda',
        11 => 'Argentina',
        12 => 'Armenia',
        13 => 'Aruba',
        14 => 'Ascension Island',
        15 => 'Australia',
        16 => 'Austria',
        17 => 'Azerbaijan',
        18 => 'Bahamas',
        19 => 'Bahrain',
        20 => 'Bangladesh',
        21 => 'Barbados',
        22 => 'Belarus',
        23 => 'Belgium',
        24 => 'Belize',
        25 => 'Benin',
        26 => 'Bermuda',
        27 => 'Bhutan',
        28 => 'Bolivia',
        29 => 'Bosnia & Herzegovina',
        30 => 'Botswana',
        31 => 'Brazil',
        32 => 'British Indian Ocean Territory',
        33 => 'British Virgin Islands',
        34 => 'Brunei',
        35 => 'Bulgaria',
        36 => 'Burkina Faso',
        37 => 'Burundi',
        38 => 'Cambodia',
        39 => 'Cameroon',
        40 => 'Canada',
        41 => 'Canary Islands',
        42 => 'Cape Verde',
        43 => 'Caribbean Netherlands',
        44 => 'Cayman Islands',
        45 => 'Central African Republic',
        46 => 'Ceuta & Melilla',
        47 => 'Chad',
        48 => 'Chile',
        49 => 'China',
        50 => 'Christmas Island',
        51 => 'Cocos (Keeling) Islands',
        52 => 'Colombia',
        53 => 'Comoros',
        54 => 'Congo - Brazzaville',
        55 => 'Congo - Kinshasa',
        56 => 'Cook Islands',
        57 => 'Costa Rica',
        58 => 'Cote d’Ivoire',
        59 => 'Croatia',
        60 => 'Cuba',
        61 => 'Curacao',
        62 => 'Cyprus',
        63 => 'Czech Republic',
        64 => 'Denmark',
        65 => 'Diego Garcia',
        66 => 'Djibouti',
        67 => 'Dominica',
        68 => 'Dominican Republic',
        69 => 'Ecuador',
        70 => 'Egypt',
        71 => 'El Salvador',
        72 => 'Equatorial Guinea',
        73 => 'Eritrea',
        74 => 'Estonia',
        75 => 'Ethiopia',
        76 => 'Falkland Islands',
        77 => 'Faroe Islands',
        78 => 'Fiji',
        79 => 'Finland',
        80 => 'France',
        81 => 'French Guiana',
        82 => 'French Polynesia',
        83 => 'French Southern Territories',
        84 => 'Gabon',
        85 => 'Gambia',
        86 => 'Georgia',
        87 => 'Germany',
        88 => 'Ghana',
        89 => 'Gibraltar',
        90 => 'Greece',
        91 => 'Greenland',
        92 => 'Grenada',
        93 => 'Guadeloupe',
        94 => 'Guam',
        95 => 'Guatemala',
        96 => 'Guernsey',
        97 => 'Guinea',
        98 => 'Guinea-Bissau',
        99 => 'Guyana',
        100 => 'Haiti',
        101 => 'Honduras',
        102 => 'Hong Kong SAR China',
        103 => 'Hungary',
        104 => 'Iceland',
        105 => 'India',
        106 => 'Indonesia',
        107 => 'Iran',
        108 => 'Iraq',
        109 => 'Ireland',
        110 => 'Isle of Man',
        111 => 'Israel',
        112 => 'Italy',
        113 => 'Jamaica',
        114 => 'Japan',
        115 => 'Jersey',
        116 => 'Jordan',
        117 => 'Kazakhstan',
        118 => 'Kenya',
        119 => 'Kiribati',
        120 => 'Kosovo',
        121 => 'Kuwait',
        122 => 'Kyrgyzstan',
        123 => 'Laos',
        124 => 'Latvia',
        125 => 'Lebanon',
        126 => 'Lesotho',
        127 => 'Liberia',
        128 => 'Libya',
        129 => 'Liechtenstein',
        130 => 'Lithuania',
        131 => 'Luxembourg',
        132 => 'Macau SAR China',
        133 => 'Macedonia',
        134 => 'Madagascar',
        135 => 'Malawi',
        136 => 'Malaysia',
        137 => 'Maldives',
        138 => 'Mali',
        139 => 'Malta',
        140 => 'Marshall Islands',
        141 => 'Martinique',
        142 => 'Mauritania',
        143 => 'Mauritius',
        144 => 'Mayotte',
        145 => 'Mexico',
        146 => 'Micronesia',
        147 => 'Moldova',
        148 => 'Monaco',
        149 => 'Mongolia',
        150 => 'Montenegro',
        151 => 'Montserrat',
        152 => 'Morocco',
        153 => 'Mozambique',
        154 => 'Myanmar (Burma)',
        155 => 'Namibia',
        156 => 'Nauru',
        157 => 'Nepal',
        158 => 'Netherlands',
        159 => 'New Caledonia',
        160 => 'New Zealand',
        161 => 'Nicaragua',
        162 => 'Niger',
        163 => 'Nigeria',
        164 => 'Niue',
        165 => 'Norfolk Island',
        166 => 'North Korea',
        167 => 'Northern Mariana Islands',
        168 => 'Norway',
        169 => 'Oman',
        170 => 'Pakistan',
        171 => 'Palau',
        172 => 'Palestinian Territories',
        173 => 'Panama',
        174 => 'Papua New Guinea',
        175 => 'Paraguay',
        176 => 'Peru',
        177 => 'Philippines',
        178 => 'Pitcairn Islands',
        179 => 'Poland',
        180 => 'Portugal',
        181 => 'Puerto Rico',
        182 => 'Qatar',
        183 => 'Reunion',
        184 => 'Romania',
        185 => 'Russia',
        186 => 'Rwanda',
        187 => 'Samoa',
        188 => 'San Marino',
        189 => 'São Tome & Principe',
        190 => 'Saudi Arabia',
        191 => 'Senegal',
        192 => 'Serbia',
        193 => 'Seychelles',
        194 => 'Sierra Leone',
        195 => 'Singapore',
        196 => 'Sint Maarten',
        197 => 'Slovakia',
        198 => 'Slovenia',
        199 => 'Solomon Islands',
        200 => 'Somalia',
        201 => 'South Africa',
        202 => 'South Georgia & South Sandwich Islands',
        203 => 'South Korea',
        204 => 'South Sudan',
        205 => 'Spain',
        206 => 'Sri Lanka',
        207 => 'St. Barthelemy',
        208 => 'St. Helena',
        209 => 'St. Kitts & Nevis',
        210 => 'St. Lucia',
        211 => 'St. Martin',
        212 => 'St. Pierre & Miquelon',
        213 => 'St. Vincent & Grenadines',
        214 => 'Sudan',
        215 => 'Suriname',
        216 => 'Svalbard & Jan Mayen',
        217 => 'Swaziland',
        218 => 'Sweden',
        219 => 'Switzerland',
        220 => 'Syria',
        221 => 'Taiwan',
        222 => 'Tajikistan',
        223 => 'Tanzania',
        224 => 'Thailand',
        225 => 'Timor-Leste',
        226 => 'Togo',
        227 => 'Tokelau',
        228 => 'Tonga',
        229 => 'Trinidad & Tobago',
        230 => 'Tristan da Cunha',
        231 => 'Tunisia',
        232 => 'Turkey',
        233 => 'Turkmenistan',
        234 => 'Turks & Caicos Islands',
        235 => 'Tuvalu',
        236 => 'U.S. Outlying Islands',
        237 => 'U.S. Virgin Islands',
        238 => 'Uganda',
        239 => 'Ukraine',
        240 => 'United Arab Emirates',
        241 => 'United Kingdom',
        242 => 'United States',
        243 => 'Uruguay',
        244 => 'Uzbekistan',
        245 => 'Vanuatu',
        246 => 'Vatican City',
        247 => 'Venezuela',
        248 => 'Vietnam',
        249 => 'Wallis & Futuna',
        250 => 'Western Sahara',
        251 => 'Yemen',
        252 => 'Zambia',
        253 => 'Zimbabwe',
    ];

    /**
     * Array of countries
     * @var array
     */
    protected static $countryList = [
        ['id' => 0, 'iso' => '--', 'name' => 'Unknown', ],
        ['id' => 1, 'iso' => 'AF', 'name' => 'Afghanistan', ],
        ['id' => 2, 'iso' => 'AX', 'name' => 'Aland Islands', ],
        ['id' => 3, 'iso' => 'AL', 'name' => 'Albania', ],
        ['id' => 4, 'iso' => 'DZ', 'name' => 'Algeria', ],
        ['id' => 5, 'iso' => 'AS', 'name' => 'American Samoa', ],
        ['id' => 6, 'iso' => 'AD', 'name' => 'Andorra', ],
        ['id' => 7, 'iso' => 'AO', 'name' => 'Angola', ],
        ['id' => 8, 'iso' => 'AI', 'name' => 'Anguilla', ],
        ['id' => 9, 'iso' => 'AQ', 'name' => 'Antarctica', ],
        ['id' => 10, 'iso' => 'AG', 'name' => 'Antigua & Barbuda', ],
        ['id' => 11, 'iso' => 'AR', 'name' => 'Argentina', ],
        ['id' => 12, 'iso' => 'AM', 'name' => 'Armenia', ],
        ['id' => 13, 'iso' => 'AW', 'name' => 'Aruba', ],
        ['id' => 14, 'iso' => 'AC', 'name' => 'Ascension Island', ],
        ['id' => 15, 'iso' => 'AU', 'name' => 'Australia', ],
        ['id' => 16, 'iso' => 'AT', 'name' => 'Austria', ],
        ['id' => 17, 'iso' => 'AZ', 'name' => 'Azerbaijan', ],
        ['id' => 18, 'iso' => 'BS', 'name' => 'Bahamas', ],
        ['id' => 19, 'iso' => 'BH', 'name' => 'Bahrain', ],
        ['id' => 20, 'iso' => 'BD', 'name' => 'Bangladesh', ],
        ['id' => 21, 'iso' => 'BB', 'name' => 'Barbados', ],
        ['id' => 22, 'iso' => 'BY', 'name' => 'Belarus', ],
        ['id' => 23, 'iso' => 'BE', 'name' => 'Belgium', ],
        ['id' => 24, 'iso' => 'BZ', 'name' => 'Belize', ],
        ['id' => 25, 'iso' => 'BJ', 'name' => 'Benin', ],
        ['id' => 26, 'iso' => 'BM', 'name' => 'Bermuda', ],
        ['id' => 27, 'iso' => 'BT', 'name' => 'Bhutan', ],
        ['id' => 28, 'iso' => 'BO', 'name' => 'Bolivia', ],
        ['id' => 29, 'iso' => 'BA', 'name' => 'Bosnia & Herzegovina', ],
        ['id' => 30, 'iso' => 'BW', 'name' => 'Botswana', ],
        ['id' => 31, 'iso' => 'BR', 'name' => 'Brazil', ],
        ['id' => 32, 'iso' => 'IO', 'name' => 'British Indian Ocean Territory', ],
        ['id' => 33, 'iso' => 'VG', 'name' => 'British Virgin Islands', ],
        ['id' => 34, 'iso' => 'BN', 'name' => 'Brunei', ],
        ['id' => 35, 'iso' => 'BG', 'name' => 'Bulgaria', ],
        ['id' => 36, 'iso' => 'BF', 'name' => 'Burkina Faso', ],
        ['id' => 37, 'iso' => 'BI', 'name' => 'Burundi', ],
        ['id' => 38, 'iso' => 'KH', 'name' => 'Cambodia', ],
        ['id' => 39, 'iso' => 'CM', 'name' => 'Cameroon', ],
        ['id' => 40, 'iso' => 'CA', 'name' => 'Canada', ],
        ['id' => 41, 'iso' => 'IC', 'name' => 'Canary Islands', ],
        ['id' => 42, 'iso' => 'CV', 'name' => 'Cape Verde', ],
        ['id' => 43, 'iso' => 'BQ', 'name' => 'Caribbean Netherlands', ],
        ['id' => 44, 'iso' => 'KY', 'name' => 'Cayman Islands', ],
        ['id' => 45, 'iso' => 'CF', 'name' => 'Central African Republic', ],
        ['id' => 46, 'iso' => 'EA', 'name' => 'Ceuta & Melilla', ],
        ['id' => 47, 'iso' => 'TD', 'name' => 'Chad', ],
        ['id' => 48, 'iso' => 'CL', 'name' => 'Chile', ],
        ['id' => 49, 'iso' => 'CN', 'name' => 'China', ],
        ['id' => 50, 'iso' => 'CX', 'name' => 'Christmas Island', ],
        ['id' => 51, 'iso' => 'CC', 'name' => 'Cocos (Keeling) Islands', ],
        ['id' => 52, 'iso' => 'CO', 'name' => 'Colombia', ],
        ['id' => 53, 'iso' => 'KM', 'name' => 'Comoros', ],
        ['id' => 54, 'iso' => 'CG', 'name' => 'Congo - Brazzaville', ],
        ['id' => 55, 'iso' => 'CD', 'name' => 'Congo - Kinshasa', ],
        ['id' => 56, 'iso' => 'CK', 'name' => 'Cook Islands', ],
        ['id' => 57, 'iso' => 'CR', 'name' => 'Costa Rica', ],
        ['id' => 58, 'iso' => 'CI', 'name' => 'Cote d’Ivoire', ],
        ['id' => 59, 'iso' => 'HR', 'name' => 'Croatia', ],
        ['id' => 60, 'iso' => 'CU', 'name' => 'Cuba', ],
        ['id' => 61, 'iso' => 'CW', 'name' => 'Curacao', ],
        ['id' => 62, 'iso' => 'CY', 'name' => 'Cyprus', ],
        ['id' => 63, 'iso' => 'CZ', 'name' => 'Czech Republic', ],
        ['id' => 64, 'iso' => 'DK', 'name' => 'Denmark', ],
        ['id' => 65, 'iso' => 'DG', 'name' => 'Diego Garcia', ],
        ['id' => 66, 'iso' => 'DJ', 'name' => 'Djibouti', ],
        ['id' => 67, 'iso' => 'DM', 'name' => 'Dominica', ],
        ['id' => 68, 'iso' => 'DO', 'name' => 'Dominican Republic', ],
        ['id' => 69, 'iso' => 'EC', 'name' => 'Ecuador', ],
        ['id' => 70, 'iso' => 'EG', 'name' => 'Egypt', ],
        ['id' => 71, 'iso' => 'SV', 'name' => 'El Salvador', ],
        ['id' => 72, 'iso' => 'GQ', 'name' => 'Equatorial Guinea', ],
        ['id' => 73, 'iso' => 'ER', 'name' => 'Eritrea', ],
        ['id' => 74, 'iso' => 'EE', 'name' => 'Estonia', ],
        ['id' => 75, 'iso' => 'ET', 'name' => 'Ethiopia', ],
        ['id' => 76, 'iso' => 'FK', 'name' => 'Falkland Islands', ],
        ['id' => 77, 'iso' => 'FO', 'name' => 'Faroe Islands', ],
        ['id' => 78, 'iso' => 'FJ', 'name' => 'Fiji', ],
        ['id' => 79, 'iso' => 'FI', 'name' => 'Finland', ],
        ['id' => 80, 'iso' => 'FR', 'name' => 'France', ],
        ['id' => 81, 'iso' => 'GF', 'name' => 'French Guiana', ],
        ['id' => 82, 'iso' => 'PF', 'name' => 'French Polynesia', ],
        ['id' => 83, 'iso' => 'TF', 'name' => 'French Southern Territories', ],
        ['id' => 84, 'iso' => 'GA', 'name' => 'Gabon', ],
        ['id' => 85, 'iso' => 'GM', 'name' => 'Gambia', ],
        ['id' => 86, 'iso' => 'GE', 'name' => 'Georgia', ],
        ['id' => 87, 'iso' => 'DE', 'name' => 'Germany', ],
        ['id' => 88, 'iso' => 'GH', 'name' => 'Ghana', ],
        ['id' => 89, 'iso' => 'GI', 'name' => 'Gibraltar', ],
        ['id' => 90, 'iso' => 'GR', 'name' => 'Greece', ],
        ['id' => 91, 'iso' => 'GL', 'name' => 'Greenland', ],
        ['id' => 92, 'iso' => 'GD', 'name' => 'Grenada', ],
        ['id' => 93, 'iso' => 'GP', 'name' => 'Guadeloupe', ],
        ['id' => 94, 'iso' => 'GU', 'name' => 'Guam', ],
        ['id' => 95, 'iso' => 'GT', 'name' => 'Guatemala', ],
        ['id' => 96, 'iso' => 'GG', 'name' => 'Guernsey', ],
        ['id' => 97, 'iso' => 'GN', 'name' => 'Guinea', ],
        ['id' => 98, 'iso' => 'GW', 'name' => 'Guinea-Bissau', ],
        ['id' => 99, 'iso' => 'GY', 'name' => 'Guyana', ],
        ['id' => 100, 'iso' => 'HT', 'name' => 'Haiti', ],
        ['id' => 101, 'iso' => 'HN', 'name' => 'Honduras', ],
        ['id' => 102, 'iso' => 'HK', 'name' => 'Hong Kong SAR China', ],
        ['id' => 103, 'iso' => 'HU', 'name' => 'Hungary', ],
        ['id' => 104, 'iso' => 'IS', 'name' => 'Iceland', ],
        ['id' => 105, 'iso' => 'IN', 'name' => 'India', ],
        ['id' => 106, 'iso' => 'ID', 'name' => 'Indonesia', ],
        ['id' => 107, 'iso' => 'IR', 'name' => 'Iran', ],
        ['id' => 108, 'iso' => 'IQ', 'name' => 'Iraq', ],
        ['id' => 109, 'iso' => 'IE', 'name' => 'Ireland', ],
        ['id' => 110, 'iso' => 'IM', 'name' => 'Isle of Man', ],
        ['id' => 111, 'iso' => 'IL', 'name' => 'Israel', ],
        ['id' => 112, 'iso' => 'IT', 'name' => 'Italy', ],
        ['id' => 113, 'iso' => 'JM', 'name' => 'Jamaica', ],
        ['id' => 114, 'iso' => 'JP', 'name' => 'Japan', ],
        ['id' => 115, 'iso' => 'JE', 'name' => 'Jersey', ],
        ['id' => 116, 'iso' => 'JO', 'name' => 'Jordan', ],
        ['id' => 117, 'iso' => 'KZ', 'name' => 'Kazakhstan', ],
        ['id' => 118, 'iso' => 'KE', 'name' => 'Kenya', ],
        ['id' => 119, 'iso' => 'KI', 'name' => 'Kiribati', ],
        ['id' => 120, 'iso' => 'XK', 'name' => 'Kosovo', ],
        ['id' => 121, 'iso' => 'KW', 'name' => 'Kuwait', ],
        ['id' => 122, 'iso' => 'KG', 'name' => 'Kyrgyzstan', ],
        ['id' => 123, 'iso' => 'LA', 'name' => 'Laos', ],
        ['id' => 124, 'iso' => 'LV', 'name' => 'Latvia', ],
        ['id' => 125, 'iso' => 'LB', 'name' => 'Lebanon', ],
        ['id' => 126, 'iso' => 'LS', 'name' => 'Lesotho', ],
        ['id' => 127, 'iso' => 'LR', 'name' => 'Liberia', ],
        ['id' => 128, 'iso' => 'LY', 'name' => 'Libya', ],
        ['id' => 129, 'iso' => 'LI', 'name' => 'Liechtenstein', ],
        ['id' => 130, 'iso' => 'LT', 'name' => 'Lithuania', ],
        ['id' => 131, 'iso' => 'LU', 'name' => 'Luxembourg', ],
        ['id' => 132, 'iso' => 'MO', 'name' => 'Macau SAR China', ],
        ['id' => 133, 'iso' => 'MK', 'name' => 'Macedonia', ],
        ['id' => 134, 'iso' => 'MG', 'name' => 'Madagascar', ],
        ['id' => 135, 'iso' => 'MW', 'name' => 'Malawi', ],
        ['id' => 136, 'iso' => 'MY', 'name' => 'Malaysia', ],
        ['id' => 137, 'iso' => 'MV', 'name' => 'Maldives', ],
        ['id' => 138, 'iso' => 'ML', 'name' => 'Mali', ],
        ['id' => 139, 'iso' => 'MT', 'name' => 'Malta', ],
        ['id' => 140, 'iso' => 'MH', 'name' => 'Marshall Islands', ],
        ['id' => 141, 'iso' => 'MQ', 'name' => 'Martinique', ],
        ['id' => 142, 'iso' => 'MR', 'name' => 'Mauritania', ],
        ['id' => 143, 'iso' => 'MU', 'name' => 'Mauritius', ],
        ['id' => 144, 'iso' => 'YT', 'name' => 'Mayotte', ],
        ['id' => 145, 'iso' => 'MX', 'name' => 'Mexico', ],
        ['id' => 146, 'iso' => 'FM', 'name' => 'Micronesia', ],
        ['id' => 147, 'iso' => 'MD', 'name' => 'Moldova', ],
        ['id' => 148, 'iso' => 'MC', 'name' => 'Monaco', ],
        ['id' => 149, 'iso' => 'MN', 'name' => 'Mongolia', ],
        ['id' => 150, 'iso' => 'ME', 'name' => 'Montenegro', ],
        ['id' => 151, 'iso' => 'MS', 'name' => 'Montserrat', ],
        ['id' => 152, 'iso' => 'MA', 'name' => 'Morocco', ],
        ['id' => 153, 'iso' => 'MZ', 'name' => 'Mozambique', ],
        ['id' => 154, 'iso' => 'MM', 'name' => 'Myanmar (Burma)', ],
        ['id' => 155, 'iso' => 'NA', 'name' => 'Namibia', ],
        ['id' => 156, 'iso' => 'NR', 'name' => 'Nauru', ],
        ['id' => 157, 'iso' => 'NP', 'name' => 'Nepal', ],
        ['id' => 158, 'iso' => 'NL', 'name' => 'Netherlands', ],
        ['id' => 159, 'iso' => 'NC', 'name' => 'New Caledonia', ],
        ['id' => 160, 'iso' => 'NZ', 'name' => 'New Zealand', ],
        ['id' => 161, 'iso' => 'NI', 'name' => 'Nicaragua', ],
        ['id' => 162, 'iso' => 'NE', 'name' => 'Niger', ],
        ['id' => 163, 'iso' => 'NG', 'name' => 'Nigeria', ],
        ['id' => 164, 'iso' => 'NU', 'name' => 'Niue', ],
        ['id' => 165, 'iso' => 'NF', 'name' => 'Norfolk Island', ],
        ['id' => 166, 'iso' => 'KP', 'name' => 'North Korea', ],
        ['id' => 167, 'iso' => 'MP', 'name' => 'Northern Mariana Islands', ],
        ['id' => 168, 'iso' => 'NO', 'name' => 'Norway', ],
        ['id' => 169, 'iso' => 'OM', 'name' => 'Oman', ],
        ['id' => 170, 'iso' => 'PK', 'name' => 'Pakistan', ],
        ['id' => 171, 'iso' => 'PW', 'name' => 'Palau', ],
        ['id' => 172, 'iso' => 'PS', 'name' => 'Palestinian Territories', ],
        ['id' => 173, 'iso' => 'PA', 'name' => 'Panama', ],
        ['id' => 174, 'iso' => 'PG', 'name' => 'Papua New Guinea', ],
        ['id' => 175, 'iso' => 'PY', 'name' => 'Paraguay', ],
        ['id' => 176, 'iso' => 'PE', 'name' => 'Peru', ],
        ['id' => 177, 'iso' => 'PH', 'name' => 'Philippines', ],
        ['id' => 178, 'iso' => 'PN', 'name' => 'Pitcairn Islands', ],
        ['id' => 179, 'iso' => 'PL', 'name' => 'Poland', ],
        ['id' => 180, 'iso' => 'PT', 'name' => 'Portugal', ],
        ['id' => 181, 'iso' => 'PR', 'name' => 'Puerto Rico', ],
        ['id' => 182, 'iso' => 'QA', 'name' => 'Qatar', ],
        ['id' => 183, 'iso' => 'RE', 'name' => 'Reunion', ],
        ['id' => 184, 'iso' => 'RO', 'name' => 'Romania', ],
        ['id' => 185, 'iso' => 'RU', 'name' => 'Russia', ],
        ['id' => 186, 'iso' => 'RW', 'name' => 'Rwanda', ],
        ['id' => 187, 'iso' => 'WS', 'name' => 'Samoa', ],
        ['id' => 188, 'iso' => 'SM', 'name' => 'San Marino', ],
        ['id' => 189, 'iso' => 'ST', 'name' => 'São Tome & Principe', ],
        ['id' => 190, 'iso' => 'SA', 'name' => 'Saudi Arabia', ],
        ['id' => 191, 'iso' => 'SN', 'name' => 'Senegal', ],
        ['id' => 192, 'iso' => 'RS', 'name' => 'Serbia', ],
        ['id' => 193, 'iso' => 'SC', 'name' => 'Seychelles', ],
        ['id' => 194, 'iso' => 'SL', 'name' => 'Sierra Leone', ],
        ['id' => 195, 'iso' => 'SG', 'name' => 'Singapore', ],
        ['id' => 196, 'iso' => 'SX', 'name' => 'Sint Maarten', ],
        ['id' => 197, 'iso' => 'SK', 'name' => 'Slovakia', ],
        ['id' => 198, 'iso' => 'SI', 'name' => 'Slovenia', ],
        ['id' => 199, 'iso' => 'SB', 'name' => 'Solomon Islands', ],
        ['id' => 200, 'iso' => 'SO', 'name' => 'Somalia', ],
        ['id' => 201, 'iso' => 'ZA', 'name' => 'South Africa', ],
        ['id' => 202, 'iso' => 'GS', 'name' => 'South Georgia & South Sandwich Islands', ],
        ['id' => 203, 'iso' => 'KR', 'name' => 'South Korea', ],
        ['id' => 204, 'iso' => 'SS', 'name' => 'South Sudan', ],
        ['id' => 205, 'iso' => 'ES', 'name' => 'Spain', ],
        ['id' => 206, 'iso' => 'LK', 'name' => 'Sri Lanka', ],
        ['id' => 207, 'iso' => 'BL', 'name' => 'St. Barthelemy', ],
        ['id' => 208, 'iso' => 'SH', 'name' => 'St. Helena', ],
        ['id' => 209, 'iso' => 'KN', 'name' => 'St. Kitts & Nevis', ],
        ['id' => 210, 'iso' => 'LC', 'name' => 'St. Lucia', ],
        ['id' => 211, 'iso' => 'MF', 'name' => 'St. Martin', ],
        ['id' => 212, 'iso' => 'PM', 'name' => 'St. Pierre & Miquelon', ],
        ['id' => 213, 'iso' => 'VC', 'name' => 'St. Vincent & Grenadines', ],
        ['id' => 214, 'iso' => 'SD', 'name' => 'Sudan', ],
        ['id' => 215, 'iso' => 'SR', 'name' => 'Suriname', ],
        ['id' => 216, 'iso' => 'SJ', 'name' => 'Svalbard & Jan Mayen', ],
        ['id' => 217, 'iso' => 'SZ', 'name' => 'Swaziland', ],
        ['id' => 218, 'iso' => 'SE', 'name' => 'Sweden', ],
        ['id' => 219, 'iso' => 'CH', 'name' => 'Switzerland', ],
        ['id' => 220, 'iso' => 'SY', 'name' => 'Syria', ],
        ['id' => 221, 'iso' => 'TW', 'name' => 'Taiwan', ],
        ['id' => 222, 'iso' => 'TJ', 'name' => 'Tajikistan', ],
        ['id' => 223, 'iso' => 'TZ', 'name' => 'Tanzania', ],
        ['id' => 224, 'iso' => 'TH', 'name' => 'Thailand', ],
        ['id' => 225, 'iso' => 'TL', 'name' => 'Timor-Leste', ],
        ['id' => 226, 'iso' => 'TG', 'name' => 'Togo', ],
        ['id' => 227, 'iso' => 'TK', 'name' => 'Tokelau', ],
        ['id' => 228, 'iso' => 'TO', 'name' => 'Tonga', ],
        ['id' => 229, 'iso' => 'TT', 'name' => 'Trinidad & Tobago', ],
        ['id' => 230, 'iso' => 'TA', 'name' => 'Tristan da Cunha', ],
        ['id' => 231, 'iso' => 'TN', 'name' => 'Tunisia', ],
        ['id' => 232, 'iso' => 'TR', 'name' => 'Turkey', ],
        ['id' => 233, 'iso' => 'TM', 'name' => 'Turkmenistan', ],
        ['id' => 234, 'iso' => 'TC', 'name' => 'Turks & Caicos Islands', ],
        ['id' => 235, 'iso' => 'TV', 'name' => 'Tuvalu', ],
        ['id' => 236, 'iso' => 'UM', 'name' => 'U.S. Outlying Islands', ],
        ['id' => 237, 'iso' => 'VI', 'name' => 'U.S. Virgin Islands', ],
        ['id' => 238, 'iso' => 'UG', 'name' => 'Uganda', ],
        ['id' => 239, 'iso' => 'UA', 'name' => 'Ukraine', ],
        ['id' => 240, 'iso' => 'AE', 'name' => 'United Arab Emirates', ],
        ['id' => 241, 'iso' => 'GB', 'name' => 'United Kingdom', ],
        ['id' => 242, 'iso' => 'US', 'name' => 'United States', ],
        ['id' => 243, 'iso' => 'UY', 'name' => 'Uruguay', ],
        ['id' => 244, 'iso' => 'UZ', 'name' => 'Uzbekistan', ],
        ['id' => 245, 'iso' => 'VU', 'name' => 'Vanuatu', ],
        ['id' => 246, 'iso' => 'VA', 'name' => 'Vatican City', ],
        ['id' => 247, 'iso' => 'VE', 'name' => 'Venezuela', ],
        ['id' => 248, 'iso' => 'VN', 'name' => 'Vietnam', ],
        ['id' => 249, 'iso' => 'WF', 'name' => 'Wallis & Futuna', ],
        ['id' => 250, 'iso' => 'EH', 'name' => 'Western Sahara', ],
        ['id' => 251, 'iso' => 'YE', 'name' => 'Yemen', ],
        ['id' => 252, 'iso' => 'ZM', 'name' => 'Zambia', ],
        ['id' => 253, 'iso' => 'ZW', 'name' => 'Zimbabwe', ],
    ];

    /**
     * Get array of countries id
     *
     * @return mixed
     */
    public static function getCountryIdList()
    {
        return array_keys(self::$isoList);
    }

    /**
     * Get array of countries iso
     *
     * @return array
     */
    public static function getCountryIsoList()
    {
        return self::$isoList;
    }

    /**
     * Get array of countries name
     *
     * @return array
     */
    public static function getCountryNameList()
    {
        return self::$nameList;
    }

    /**
     * Get array of countries
     *
     * @return array
     */
    public static function getCountryList()
    {
        return self::$countryList;
    }

    /**
     * Get english short country name by id
     *
     * @param $countryId
     * @return string|null
     */
    public static function getCountryNameById($countryId)
    {
        return array_key_exists($countryId, self::$nameList) ? self::$nameList[$countryId] : null;
    }

    /**
     * Get ISO 3166-1 alpha-2 country code by id
     *
     * @param integer $countryId
     * @return string|null
     */
    public static function getCountryIsoById($countryId)
    {
        return array_key_exists($countryId, self::$isoList) ? self::$isoList[$countryId] : null;
    }

    /**
     * Get country id by ISO 3166-1 alpha-2 country code. Return id of "Unknown" country on code not exists
     *
     * @param string $iso ISO 3166-1 alpha-2 country code
     * @return int
     */
    public static function getIdByCountryIsoCode($iso)
    {

        return (int) array_search(strtoupper($iso), self::$isoList);
    }
}
